FROM alpine:latest

# Устанавливаем необходимые пакеты
RUN apk add --no-cache bash

# Рабочая директория
WORKDIR /app

# Копируем скрипт создания APK
COPY create_apk.sh /app/

# Делаем скрипт исполняемым
RUN chmod +x /app/create_apk.sh

# Команда по умолчанию
CMD ["/app/create_apk.sh"]
